'use client';

import { ScoreCard } from '@/components/app/ScoreCard';
import { WaitlistForm } from '@/components/marketing/WaitlistForm';
import { AnimatedSection } from '@/components/shared/AnimatedSection';
import type { JudgeResult } from '@/types/api';
import type { FarmingFlag } from '@/lib/constants';

interface ScorePageClientProps {
  composite: number;
  teaching: number;
  originality: number;
  impact: number;
  flag: FarmingFlag;
}

export function ScorePageClient({
  composite,
  teaching,
  originality,
  impact,
  flag,
}: ScorePageClientProps) {
  const result: JudgeResult = {
    compositeScore: composite,
    teachingValue: teaching,
    originality,
    communityImpact: impact,
    farmingFlag: flag,
    farmingExplanation: '',
    dimensionExplanations: {
      teachingValue: '',
      originality: '',
      communityImpact: '',
    },
    scoredAt: new Date().toISOString(),
  };

  return (
    <main className="min-h-screen">
      {/* Score display */}
      <section className="py-24 flex flex-col items-center px-4 sm:px-6">
        <AnimatedSection className="text-center mb-10">
          <p className="font-mono text-[10px] uppercase tracking-[0.2em] text-muted-foreground mb-3">
            AI Judge Result
          </p>
          <h1 className="font-heading text-3xl sm:text-4xl font-bold text-foreground mb-2">
            Score: <span className="text-primary">{composite}/100</span>
          </h1>
          <p className="font-body text-muted-foreground max-w-[480px] mx-auto">
            This score was generated by the AI Judge. It evaluates contributions by
            teaching value, originality, and community impact — not likes or volume.
          </p>
        </AnimatedSection>

        <div className="flex justify-center">
          <ScoreCard result={result} showShare />
        </div>
      </section>

      {/* Waitlist CTA */}
      <section className="py-16 bg-card/30" id="waitlist">
        <div className="max-w-[720px] mx-auto px-4 sm:px-6">
          <AnimatedSection className="text-center mb-10">
            <p className="font-mono text-[10px] uppercase tracking-[0.2em] text-muted-foreground mb-3">
              Think You Can Beat This?
            </p>
            <h2 className="font-heading text-2xl sm:text-3xl font-bold text-foreground mb-4">
              Get Your Own Score
            </h2>
            <p className="font-body text-muted-foreground max-w-[480px] mx-auto">
              Join the waitlist, connect your wallet, and let the AI Judge score your
              contributions. Real quality. Real rewards.
            </p>
          </AnimatedSection>

          <AnimatedSection>
            <WaitlistForm />
          </AnimatedSection>
        </div>
      </section>
    </main>
  );
}
